Repository nank1ro/flutter-shadcn-ui, pull requests merged in 2024-10, with the labels that each got.

#157 feat: select deselection
  CHANGELOG.md
  docs/src/content/docs/Components/select.mdx
  example/lib/pages/select.dart
  example/lib/pages/select_form_field.dart
  lib/src/components/form/fields/select.dart
  lib/src/components/select.dart
  pubspec.yaml
Labels: feature

#158 Feat/select multiple options
  CHANGELOG.md
  docs/src/content/docs/Components/select.mdx
  example/lib/pages/select.dart
  lib/src/components/form/fields/select.dart
  lib/src/components/select.dart
  playground/lib/pages/select.dart
  pubspec.yaml
Labels: feature

#162 feat: Add custom `headers` support to `ShadImage` for network images
  CHANGELOG.md
  example/lib/pages/image.dart
  lib/src/components/image.dart
  playground/lib/pages/image.dart
  pubspec.yaml
Labels: feature

#164 feat: radio group properties
  CHANGELOG.md
  example/lib/pages/radio_group.dart
  example/lib/pages/radio_group_form_field.dart
  lib/src/components/form/fields/radio.dart
  lib/src/components/radio.dart
  lib/src/theme/components/radio.dart
  lib/src/theme/themes/default_theme_no_secondary_border_variant.dart
  lib/src/theme/themes/default_theme_variant.dart
  pubspec.yaml
Labels: feature

#131 feat/calendar
  CHANGELOG.md
  README.md
  docs/astro.config.mjs
  docs/package-lock.json
  docs/package.json
  docs/public/shadcn-banner.png
  docs/src/content/docs/Components/calendar.mdx
  docs/src/content/docs/index.md
  example/lib/common/properties/bool_property.dart
  example/lib/main.dart
  example/lib/pages/calendar.dart
  lib/shadcn_ui.dart
  lib/src/components/calendar.dart
  lib/src/theme/components/calendar.dart
  lib/src/theme/components/resizable.dart
  lib/src/theme/data.dart
  lib/src/theme/themes/base.dart
  lib/src/theme/themes/default_theme_no_secondary_border_variant.dart
  lib/src/theme/themes/default_theme_variant.dart
  lib/src/utils/extensions/breakpoints.dart
  lib/src/utils/extensions/date_time.dart
  lib/src/utils/extensions/duration.dart
  playground/lib/main.dart
  playground/lib/pages/calendar.dart
  pubspec.yaml
Labels: feature

#168 docs: 166
  docs/src/content/docs/Components/toast.mdx
Labels: documentation

#169 chore: update image import due to wasm
  CHANGELOG.md
  lib/src/components/image.dart
  pubspec.yaml
Labels: chore

#174 fix: select initial values
  CHANGELOG.md
  lib/src/components/select.dart
  pubspec.yaml
Labels: bug

#180 fix: scroll behavior of app
  CHANGELOG.md
  lib/src/app.dart
  pubspec.yaml
Labels: bug

#182 docs: add packages section
  docs/astro.config.mjs
  docs/src/content/docs/packages.md
  lib/shadcn_ui.dart
Labels: documentation
