Repository nank1ro/flutter-shadcn-ui, pull requests merged in 2024-09, with the labels that each got.

#130 feat/context-menu
  CHANGELOG.md
  README.md
  example/lib/common/base_scaffold.dart
  example/lib/main.dart
  example/lib/pages/context_menu.dart
  example/lib/pages/select.dart
  lib/shadcn_ui.dart
  lib/src/app.dart
  lib/src/components/button.dart
  lib/src/components/context_menu.dart
  lib/src/components/form/form.dart
  lib/src/components/popover.dart
  lib/src/raw_components/focusable.dart
  lib/src/raw_components/portal.dart
  lib/src/theme/components/context_menu.dart
  lib/src/theme/components/decorator.dart
  lib/src/theme/data.dart
  lib/src/theme/themes/base.dart
  lib/src/theme/themes/default_theme_no_secondary_border_variant.dart
  lib/src/theme/themes/default_theme_variant.dart
  lib/src/utils/gesture_detector.dart
  lib/src/utils/mouse_area.dart
  lib/src/utils/provider.dart
  playground/lib/main.dart
  playground/lib/pages/accordion.dart
  playground/lib/pages/alert.dart
  playground/lib/pages/badge.dart
  playground/lib/pages/button.dart
  playground/lib/pages/card.dart
  playground/lib/pages/context_menu.dart
  playground/lib/pages/dialog.dart
  playground/lib/pages/form.dart
  playground/lib/pages/resizable.dart
  playground/lib/pages/select.dart
  playground/lib/pages/sheet.dart
  playground/lib/pages/toast.dart
  playground/lib/pages/typography.dart
  pubspec.yaml
Labels: enhancement

#134 fix/native-context-menu
  CHANGELOG.md
  example/.gitignore
  lib/src/app.dart
  lib/src/components/context_menu.dart
  lib/src/components/popover.dart
  lib/src/components/tabs.dart
  lib/src/raw_components/portal.dart
  pubspec.yaml
Labels: bug

#138 fix/input-read-only-focus
  CHANGELOG.md
  lib/src/components/form/field.dart
  lib/src/components/form/fields/input.dart
  lib/src/components/input.dart
  pubspec.yaml
Labels: bug

#142 feat: added text selection menu
  example/.metadata
  lib/src/components/input.dart
Labels: enhancement

#145 feat/docs
  docs/.gitignore
  docs/README.md
  docs/astro.config.mjs
  docs/package-lock.json
  docs/package.json
  docs/public/favicon.svg
  docs/src/assets/shadcn-banner.png
  docs/src/components/Preview.astro
  docs/src/content/config.ts
  docs/src/content/docs/shadcn-ui/Components/accordion.mdx
  docs/src/content/docs/shadcn-ui/Components/alert.mdx
  docs/src/content/docs/shadcn-ui/Components/avatar.mdx
  docs/src/content/docs/shadcn-ui/Components/badge.mdx
  docs/src/content/docs/shadcn-ui/Components/button.mdx
  docs/src/content/docs/shadcn-ui/Components/card.mdx
  docs/src/content/docs/shadcn-ui/Components/checkbox.mdx
  docs/src/content/docs/shadcn-ui/Components/context-menu.mdx
  docs/src/content/docs/shadcn-ui/Components/dialog.mdx
  docs/src/content/docs/shadcn-ui/Components/form.mdx
  docs/src/content/docs/shadcn-ui/Components/image.mdx
  docs/src/content/docs/shadcn-ui/Components/input.mdx
  docs/src/content/docs/shadcn-ui/Components/popover.mdx
  docs/src/content/docs/shadcn-ui/Components/progress.mdx
  docs/src/content/docs/shadcn-ui/Components/radio-group.mdx
  docs/src/content/docs/shadcn-ui/Components/resizable.mdx
  docs/src/content/docs/shadcn-ui/Components/select.mdx
  docs/src/content/docs/shadcn-ui/Components/sheet.mdx
  docs/src/content/docs/shadcn-ui/Components/slider.mdx
  docs/src/content/docs/shadcn-ui/Components/switch.mdx
  docs/src/content/docs/shadcn-ui/Components/table.mdx
  docs/src/content/docs/shadcn-ui/Components/tabs.mdx
  docs/src/content/docs/shadcn-ui/Components/toast.mdx
  docs/src/content/docs/shadcn-ui/Components/tooltip.mdx
  docs/src/content/docs/shadcn-ui/Theme/data.md
  docs/src/content/docs/shadcn-ui/Utils/decorator.md
  docs/src/content/docs/shadcn-ui/Utils/responsive.md
  docs/src/content/docs/shadcn-ui/index.md
  docs/src/content/docs/shadcn-ui/typography.mdx
  docs/src/env.d.ts
  docs/tsconfig.json
Labels: documentation

#149 fix/mouse-area-trackpad-kind
  CHANGELOG.md
  lib/src/utils/mouse_area.dart
  pubspec.yaml
Labels: bug

#151 fix/context-menu-right-click
  CHANGELOG.md
  lib/shadcn_ui.dart
  lib/src/app.dart
  lib/src/components/context_menu.dart
  lib/src/components/popover.dart
  lib/src/utils/disable_context_menu/disable_context_menu.dart
  lib/src/utils/disable_context_menu/non_web.dart
  lib/src/utils/disable_context_menu/web.dart
  pubspec.yaml
Labels: bug

#153 docs/add pic gen
  docs/astro.config.mjs
Labels: documentation
