Repository nank1ro/flutter-shadcn-ui, pull requests merged in 2024-11, with the labels that each got.

#187 fix: select with options builder
  CHANGELOG.md
  lib/src/components/form/fields/select.dart
  lib/src/components/select.dart
  pubspec.yaml
Labels: bug

#190 fix/decoration-merge
  CHANGELOG.md
  lib/src/components/alert.dart
  lib/src/components/calendar.dart
  lib/src/components/context_menu.dart
  lib/src/components/resizable.dart
  lib/src/components/tabs.dart
  lib/src/components/tooltip.dart
  pubspec.yaml
Labels: bug

#192 Fix/sheet and dialog children constraints
  CHANGELOG.md
  lib/src/components/dialog.dart
  pubspec.yaml
Labels: bug

#194 chore: remove unnecessary track color in switch
  lib/src/components/form/fields/switch.dart
  lib/src/components/switch.dart
  lib/src/theme/components/switch.dart
Labels: chore

#197 docs: update button docs to child from text
  docs/src/content/docs/Components/button.mdx
Labels: documentation

#198 Docs/fix wrong code samples
  docs/src/content/docs/Components/card.mdx
  docs/src/content/docs/Components/checkbox.mdx
  docs/src/content/docs/Components/context-menu.mdx
  docs/src/content/docs/Components/dialog.mdx
  docs/src/content/docs/Components/input.mdx
  docs/src/content/docs/Components/popover.mdx
  docs/src/content/docs/Components/select.mdx
  docs/src/content/docs/Components/switch.mdx
  docs/src/content/docs/Components/table.mdx
  docs/src/content/docs/Components/tabs.mdx
  docs/src/content/docs/Components/toast.mdx
Labels: documentation

#202 Fix onChanged being called on every controller update
  lib/src/components/slider.dart
Labels: bug

#195 feat/time-picker
  CHANGELOG.md
  README.md
  docs/src/content/docs/Components/form.mdx
  docs/src/content/docs/Components/time-picker.mdx
  example/lib/main.dart
  example/lib/pages/time_picker.dart
  example/lib/pages/time_picker_form_field.dart
  lib/shadcn_ui.dart
  lib/src/components/form/fields/time_picker.dart
  lib/src/components/input.dart
  lib/src/components/time_picker.dart
  lib/src/theme/components/time_picker.dart
  lib/src/theme/data.dart
  lib/src/theme/themes/base.dart
  lib/src/theme/themes/default_theme_no_secondary_border_variant.dart
  lib/src/theme/themes/default_theme_variant.dart
  playground/analysis_options.yaml
  playground/lib/main.dart
  playground/lib/pages/form.dart
  playground/lib/pages/time_picker.dart
  playground/pubspec.yaml
  pubspec.yaml
Labels: feature
