Repository nank1ro/flutter-shadcn-ui, pull requests merged in 2024-05, with the labels that each got.

#60 fix/tooltip mobile
  example/pubspec.yaml
  lib/shadcn_ui.dart
  lib/src/components/badge.dart
  lib/src/components/button.dart
  lib/src/components/select.dart
  lib/src/components/tooltip.dart
  lib/src/theme/components/tooltip.dart
  lib/src/theme/data.dart
  lib/src/theme/themes/base.dart
  lib/src/theme/themes/component_default.dart
  lib/src/utils/gesture_detector.dart
Labels: bug

#57 Add the newly added Input OTP to the "Roadmap"
  README.md
Labels: documentation

#59 fix/resizable tap region
  CHANGELOG.md
  example/.metadata
  example/lib/pages/resizable.dart
  lib/src/components/resizable.dart
  lib/src/theme/components/resizable.dart
  lib/src/theme/themes/component_default.dart
  lib/src/utils/gesture_detector.dart
  pubspec.yaml
Labels: bug

#65 refactor/accordion api standardization
  CHANGELOG.md
  lib/shadcn_ui.dart
  lib/src/components/accordion.dart
  lib/src/theme/components/accordion.dart
  lib/src/theme/themes/component_default.dart
  lib/src/utils/effects.dart
Labels: chore

#67 Fix table row indices to handle headers and footers correctly
  lib/src/components/table.dart
Labels: bug

#72 fix/input-on-tap
  CHANGELOG.md
  lib/src/components/form/fields/input.dart
  lib/src/components/input.dart
  pubspec.yaml
Labels: bug
